language: php

matrix:
  include:
    - php: 5.4
      env: 
        - UUID_GENERATOR='rhumsaa/uuid "^2.9"'
        - HTTP_CLIENT='guzzle/guzzle'

before_install:
  - composer selfupdate

install:
  - composer update
  - composer require {$UUID_GENERATOR}
  - composer require {$HTTP_CLIENT}

script:
  - vendor/bin/phpspec run --format=pretty spec/