language: php

matrix:
  include:
    - php: 5.4
      env:
        - COMPOSER_PATH=.
        - TESTS=ops/scripts/travis/unit.sh
#    - php: 5.4
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_1.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh
#    - php: 5.4
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_2.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh
#    - php: 5.4
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_3.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh
    - php: 5.5
      env:
        - COMPOSER_PATH=.
        - TESTS=ops/scripts/travis/unit.sh
#    - php: 5.5
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_1.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh
#    - php: 5.5
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_2.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh
#    - php: 5.5
#      env:
#        - COMPOSER_PATH=ops/composer/ramsey_uuid_3.0
#        - TESTS=ops/scripts/travis/ramsey_uuid.sh

before_install:
  - composer selfupdate

install:
  - cp -f $COMPOSER_PATH/composer.json ./composer.json
  - cp -f $COMPOSER_PATH/composer.lock ./composer.lock
  - composer install

script:
  - sh $SCRIPT