language: php

matrix:
  include:
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/vanilla
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_1.0
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_2.0
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_3.0
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_4.0
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_5.0
    - php: 5.4
      env:
        - COMPOSER_PATH=ops/composer/guzzle_guzzle_3.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/vanilla
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_1.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_2.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_3.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_4.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_5.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_6.0
    - php: 5.5
      env:
        - COMPOSER_PATH=ops/composer/guzzle_guzzle_3.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/vanilla
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_1.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_2.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/ramsey_uuid_3.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_4.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_5.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/guzzlehttp_guzzle_6.0
    - php: 5.6
      env:
        - COMPOSER_PATH=ops/composer/guzzle_guzzle_3.0

before_install:
  - composer selfupdate

install:
  - mv ./composer.json ./composer.json.back 
  - mv ./composer.lock ./composer.lock.back 
  - cp -f $COMPOSER_PATH/composer.json ./composer.json
  - cp -f $COMPOSER_PATH/composer.lock ./composer.lock
  - composer install

script:
  - bin/phpspec run --format=pretty
