language: php

matrix:
  include:
    - php: 5.4
      env: 
        - UUID_GENERATOR='rhumsaa/uuid ^2.0'
        - HTTP_CLIENT='guzzle/guzzle ^3.0'
    - php: 5.4
      env:
        - UUID_GENERATOR='ramsey/uuid ^3.0'
        - HTTP_CLIENT='guzzlehttp/guzzle ^6.0'

before_install:
  - composer selfupdate

install:
  - composer update
  - composer require $UUID_GENERATOR
  - composer require $HTTP_CLIENT

script:
  - vendor/bin/phpspec run --format=pretty spec/